name: Build Backend

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: AliciaSchiochetSouza
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push Docker image to GitHub Container Registry
      - name: Build and Push Docker Image
        run: |
          REPO_NAME=fabsoftb_alicia_jose-2025-1-b
          docker build -t ghcr.io/AliciaSchiochetSouza/$REPO_NAME/projfabsoftescolamusica:latest ./projfabsoftescolamusica
          docker push ghcr.io/AliciaSchiochetSouza/$REPO_NAME/projfabsoftescolamusica:latest