name: Build and Run Spring Boot Backend

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up JDK
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push Docker image to GitHub Container Registry
      - name: Build and Push Docker Image
        run: |
          docker build -t ghcr.io/AliciaSchiochetSouza/fabsoftb_Alicia_Jose-2025-1-b/rojfabsoftescolamusica:latest ./projfabsoftescolamusica
          docker push ghcr.io/AliciaSchiochetSouza/fabsoftb_Alicia_Jose-2025-1-b/rojfabsoftescolamusica:latest